"""Ingestion package exposing high level APIs."""

from .chunking import chunk_text
from .parsers import (
    Chunk,
    extract_html_text,
    read_csv_text,
    read_docx_text,
    read_txt_text,
    read_xlsx_text,
)
from .service import (
    EMBEDDING_MODEL,
    TextEmbedding,
    cancel_job,
    get_job,
    ingest_local,
    ingest_source,
    ingest_url,
    ingest_urls,
    insert_chunks,
    list_jobs,
    read_job_log,
    read_md_text,
    read_pdf_text,
    read_url_text,
    reindex_source,
    rerun_job,
    upsert_document,
)

__all__ = [
    "Chunk",
    "extract_html_text",
    "read_csv_text",
    "read_docx_text",
    "read_txt_text",
    "read_xlsx_text",
    "read_md_text",
    "read_pdf_text",
    "read_url_text",
    "chunk_text",
    "upsert_document",
    "insert_chunks",
    "ingest_local",
    "ingest_url",
    "ingest_urls",
    "ingest_source",
    "reindex_source",
    "rerun_job",
    "cancel_job",
    "get_job",
    "list_jobs",
    "read_job_log",
    "TextEmbedding",
    "EMBEDDING_MODEL",
]
